const restaurants = [
  {
    name: "The Gourmet Kitchen",
    rating: 5,
    location: "London",
    image: "https://via.assets.so/game.png?id=1&q=95&w=360&h=360&fit=fill",
    promotion: true,
    cost: 4,
  },
  {
    name: "Spice Garden",
    rating: 4,
    location: "Manchester",
    image: "https://via.assets.so/game.png?id=2&q=95&w=360&h=360&fit=fill",
    promotion: false,
    cost: 3,
  },
  {
    name: "Sushi Delight",
    rating: 5,
    location: "Birmingham",
    image: "https://via.assets.so/game.png?id=3&q=95&w=360&h=360&fit=fill",
    promotion: true,
    cost: 5,
  },
  {
    name: "La Bella Pasta",
    rating: 4,
    location: "Liverpool",
    image: "https://via.assets.so/game.png?id=4&q=95&w=360&h=360&fit=fill",
    promotion: false,
    cost: 3,
  },
  {
    name: "Burger Haven",
    rating: 4,
    location: "Leeds",
    image: "https://via.assets.so/game.png?id=5&q=95&w=360&h=360&fit=fill",
    promotion: true,
    cost: 2,
  },
  {
    name: "The Curry Palace",
    rating: 3,
    location: "Glasgow",
    image: "https://via.assets.so/game.png?id=6&q=95&w=360&h=360&fit=fill",
    promotion: false,
    cost: 4,
  },
  {
    name: "Dragon's Den",
    rating: 5,
    location: "Edinburgh",
    image: "https://via.assets.so/game.png?id=7&q=95&w=360&h=360&fit=fill",
    promotion: true,
    cost: 5,
  },
  {
    name: "Pizza World",
    rating: 3,
    location: "Sheffield",
    image: "https://via.assets.so/game.png?id=8&q=95&w=360&h=360&fit=fill",
    promotion: false,
    cost: 2,
  },
  {
    name: "Taco Fiesta",
    rating: 5,
    location: "Bristol",
    image: "https://via.assets.so/game.png?id=9&q=95&w=360&h=360&fit=fill",
    promotion: true,
    cost: 3,
  },
  {
    name: "Ocean Grill",
    rating: 4,
    location: "Nottingham",
    image: "https://via.assets.so/game.png?id=10&q=95&w=360&h=360&fit=fill",
    promotion: false,
    cost: 5,
  },
];

export default restaurants;
